'use client';

import './globals.css';
import { nohemi } from '@/app/localFont';
import { useState } from 'react';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const [theme, setTheme] = useState(
    window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
  );
  return (
    <html className={theme} lang="en">
      <body className={`${nohemi.variable} `}>{children}</body>
    </html>
  );
}
