import "./globals.css";
import { nohemi } from "../../public/assets/font/localFont";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nohemi.variable}`}>{children}</body>
    </html>
  );
}
